### ISSUE TITLE
I need help configuring ffmpeg in my application.

### ISSUE THREAD

**Issue by IamBinishMathew** [Javernaut/ffmpeg-android-maker#29]
Sorry to submit this as an issue. But I had no way to contact you outside github.
Here is my problem,

2020-06-07 18:19:15.686 29697-29697/com.bini.bee.studio E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bini.bee.studio, PID: 29697
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libavutil.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.bini.bee.studio.javaBee.<clinit>(javaBee.java:6)
        at com.bini.bee.studio.VideoEditorActivity.onClick(VideoEditorActivity.java:102)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27355)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
2020-06-07 18:19:15.693 29697-29697/com.bini.bee.studio I/Process: Sending signal. PID: 29697 SIG: 9

My CMake :

cmake_minimum_required(VERSION 3.4.1)

set(ffmpeg_dir ${CMAKE_SOURCE_DIR}/src/main/nativeLibs)
set(ffmpeg_libs ${ffmpeg_dir}/lib/${ANDROID_ABI})

include_directories(${ffmpeg_dir}/include/${ANDROID_ABI})

set(
        # List variable name
        ffmpeg_libs_names
        # Values in the list
        avutil avformat avcodec swscale)

foreach (ffmpeg_lib_name ${ffmpeg_libs_names})
    add_library(
            ${ffmpeg_lib_name}
            SHARED
            IMPORTED)
    set_target_properties(
            ${ffmpeg_lib_name}
            PROPERTIES
            IMPORTED_LOCATION
            ${ffmpeg_libs}/lib${ffmpeg_lib_name}.so)
endforeach ()

add_library(
        # Name for a library to build
        nativeLib
        # Type of a library
        SHARED
        # All cpp files to compile
        src/main/nativeLibs/nativeBee.cpp)

target_link_libraries(
        # Library to link
        nativeLib
        # List of libraries to link against:
        # Library for writing messages in LogCat
        log
        # Library for processing Bitmap objects
        jnigraphics
        # FFmpeg libraries
        ${ffmpeg_libs_names})

I have analysed the apk , it is only 1.85 mb.
my library nativeLib is present inside the apk. I don't know if the ffmpeg libraries are linked to it.

**Comment by IamBinishMathew** [comment]
@Javernaut How can I communicate with you outside github?

**Comment by Javernaut** [comment]
Hi there.
I guess you just didn't setup gradle script to pick compiled FFmpeg libraries.
Here is how you can do it: https://github.com/Javernaut/WhatTheCodec/blob/master/app/build.gradle#L26

Keep in mind that ffmpeg-android-maker is placed just into this repo and the output binaries are picked by relative path.

**Comment by IamBinishMathew** [comment]
I have done this in my build.gradle file 
It points to src/main/nativeLibs

**Comment by Javernaut** [comment]
@IamBinishMathew , 
Here is the reference code with the comment:
```
sourceSets {
        main {
            // let gradle pack the shared library into apk
            jniLibs.srcDirs = ['../ffmpeg-android-maker/output/lib']
        }
    }
```

The value of `jniLibs.srcDirs` should point to the output/lib directory of your copy of ffmpeg-android-maker and not to the src/main/nativeLibs, unless you moved the whole content of output/lib there.

**Comment by IamBinishMathew** [comment]
I have solved this problem. But I have a new problem.
When I'm opening codec using,

if(avcodec_open2(pCodecCtx, pCodec, NULL)<0) {
        return -1; // Could not open codec
    }

It gives me an error:

2020-06-09 00:04:39.394 26075-26075/com.bini.bee.studio A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 26075 (bini.bee.studio), pid 26075 (bini.bee.studio)

I tried replacing NULL with nullptr.

Do you have a solution??

How can I communicate with you outside github. ?
Every time I have to create a new issue thread to get your attention.
Can I have your email address or telegram username?

**Comment by Javernaut** [comment]
My account on Github has an email.

As for your problem - it is hard to say what causes that. It depends on how the FFmpeg was built and what particular codec you are trying to open.

**Comment by IamBinishMathew** [comment]
I'm tried to open HEVC and H264. both gave me error.
I'm closing this issue.
I will email you.
