### ISSUE TITLE
got a UnsatisfiedLinkError while running on Android 5.1 devices. 

### ISSUE THREAD

**Issue by wolfheros** [Javernaut/ffmpeg-android-maker#50]
compiled and running is fine on device Android 9.0, but failed on android device 5.1, here is the error message:

- java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_audio_fifo_peek_at" referenced by "libavfilter.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.joygames.joyplayer.MainActivity.<clinit>(MainActivity.java:30)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1606)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)
06-08 11:32:29.482 5336-5336/? I/Process: Sending signal. PID: 5336 SIG: 9

Its really wired for me. cause it all working fine on high version devices. and the abi using is v7a.

**Comment by Javernaut** [comment]
@wolfheros 
Hello and sorry for such a long gap.

Is this issue still relevant to you?

**Comment by Javernaut** [comment]
I think this is already an outdated issue.

Just to leave a hint of a direction to consider: the failure occurs on native library loading rather than on a native method invocation, so it is either (1) the native libraries (*.so) are imported in a wrong order (a library-dependency is imported later than a dependant library) or (2) the respective library where the av_audio_fifo_peek_at function usually resides now doesn't have it for a reason (like because of stripping).
