### ISSUE TITLE
app crashes issues

### ISSUE THREAD

**Issue by riyaznaz** [Javernaut/ffmpeg-android-maker#69]
I am trying launch app this issue is found. Please help me.  My config setup given below. 
using latest gradle plugin 7.2.2

  compileSdk 32
    ndkVersion '25.0.8775105'

    defaultConfig {
        minSdk 24
        targetSdk 32

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    ndk {
         abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
     }
    
    }

2022-08-20 19:47:53.227 8058-8058/com.sx.videoeditor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sx.videoeditor, PID: 8058
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libswresample.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.butterfly.video_editor_lib.VideoEditorLibCreator.<clinit>(VideoEditorLibCreator.kt:10)
        at com.sx.videoeditor.MainActivity.onCreate(MainActivity.kt:22)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Javernaut** [comment]
Hello.

There can be several reasons for that:
- You didn't build the respective library (swresample).
- You didn't package the library with the app. [Here](https://github.com/Javernaut/MediaFile/blob/master/media-file/CMakeLists.txt#L12) you can find the example of the libraries that are actually get packaged with the app.
- You didn't load the library in the proper order. See [here](https://github.com/Javernaut/MediaFile/blob/master/media-file/src/main/java/io/github/javernaut/mediafile/creator/MediaFileBuilder.kt#L172) for details.

**Comment by riyaznaz** [comment]
Thank you for your response.
 
I did everything perfect but i am still getting same error and app crashing.

I am testing android api level 28 device.

**Comment by Javernaut** [comment]
Can you open your apk or aar file with with Android Studio to see what actually is packaged in lib directory?

**Comment by riyaznaz** [comment]
i see lib given below. but i can't see "libswresample.so" file but build it. i see the libswresample.so in output lib folder

x86_64
   libavcodec.so
   libavformat.so
   libavutil.so
   libswscale.so
   libvideo-editor-lib.so

x86
   libavcodec.so
   libavformat.so
   libavutil.so
   libswscale.so
   libvideo-editor-lib.so

armeabi-v7a
   libavcodec.so
   libavformat.so
   libavutil.so
   libswscale.so
   libvideo-editor-lib.so

arm64-v8a
   libavcodec.so
   libavformat.so
   libavutil.so
   libswscale.so
   libvideo-editor-lib.so

**Comment by Javernaut** [comment]
Then make sure you list the swresample in your CMakeLists.txt, as [here](https://github.com/Javernaut/MediaFile/blob/master/media-file/CMakeLists.txt#L12).

**Comment by riyaznaz** [comment]
Thank you so much for your help. finally i found the issue. i have learnt a lot from this issues. I am new to NDK development. That's why i am facing issues without having perfect knowledge of NDK. once again thank you much for this ffmpeg_android_maker library. this makes very easier for development.
